name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "30d71331f3064c6489f5ff450b47b837"				#KV数据库id
